version: "3"
services:
  db:
    container_name: njord_local_db
    image: postgres:12.1-alpine
    ports:
      - "3002:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: njord
      POSTGRES_USER: njord
      POSTGRES_PASSWORD: admin
    command:
      - "postgres"
      - "-c"
      - "listen-addresses=*"
